- app/pkg/config/config.go
This PR updates the default image registry references to point to a new location via GitHub Container Registry.
> Update default image registry references

- app/cmd/config.go
- app/pkg/agent/agent.go
- app/pkg/config/azure.go
- app/pkg/config/config.go
- app/pkg/oai/client.go
- app/pkg/oai/client_test.go
- docs/content/en/docs/azure/_index.md
* Update the config command to set OpenAI deployments.
* Add documentation for using Azure OpenAI.
> Add support for AzureAI

- app/pkg/agent/agent.go
- app/pkg/config/config.go
- app/pkg/config/const.go
- app/pkg/oai/client.go
- app/pkg/oai/client_test.go
- docs/content/en/docs/ollama/_index.md
- Add 'AgentConfig' struct to 'config' package with a 'Model' field for specifying the model to use for completions
- Set default configuration for the 'AgentConfig' model to 'openai.GPT3Dot5Turbo0125'
- Update 'agent' package to handle missing AgentConfig in configuration and log an error
- Update 'oai' package to handle missing OpenAI configuration and custom BaseURL, and log BaseURL usage
- Add 'DefaultModel' constant for Ollama model name to 'const.go' in 'config' package
- Add a manual test for Ollama usage with 'Test_Ollama' in 'client_test.go' with a check for 'GITHUB_ACTIONS' environment variable
- Add documentation for using Ollama with Foyle in 'docs/content/en/docs/ollama/_index.md'
- Include steps for configuring Foyle to use Ollama's baseURL and model in the documentation
> Add support for configuring and using Ollama models with Foyle:

- frontend/foyle/Dockerfile
- frontend/foyle/build.sh
- frontend/vscode/web-assets/Dockerfile
- frontend/vscode/web-assets/build.sh
* Add build arguments for version, date, and commit information to Docerfile and update build script to include generating a version.json file with this information.
* Related to #45 
* We need to add information to the frontend assets so we know what version it is.
* We do this by adding a JSON file during the build process
> Attach version information to downloaded assets 

- app/pkg/application/app.go
- app/pkg/config/config.go
* We need to produce machine readable JSON logs
* We do this by creating two separate logging cores
* This way we can have a consoleEncoder that potentially still writes in human readable format
Related to #7
> Setup logging for human feedback

- frontend/foyle/package.json
- frontend/foyle/src/web/controller.ts
- frontend/foyle/src/web/debug.ts
- frontend/foyle/src/web/extension.ts
The bug was in how we were converting the current cell to a block before sending it to the server.
We weren't using the converters that we wrote. We were using some other code that wasn't setting the metadata and therefore copying the block id to the request.
* I also added a vscode function that will print the cell metadata. This is useful for debugging and troubleshooting.
related to #7
> Fix bug with execute not sending blockIDs to the server

- docs/content/en/docs/getting-started/_index.md
- docs/content/en/docs/markdown/_index.md
- frontend/foyle/package.json
- frontend/foyle/src/web/controller.ts
- frontend/foyle/src/web/extension.ts
- frontend/foyle/src/web/markdown.ts
- frontend/foyle/src/web/markdownParser.ts
- frontend/foyle/src/web/test/suite/markdown.test.ts
* Use VSCode's markdown notebook extension as the basis for markdown support
* To support markdown we define a new new notebook type foyle-notebook-md and then register another copy of the controller for it
* The reason we need to register a new notebook-type is because serializers appear to be linked to the notebook-type. Within the serializer it didn't seem like we could easily get the original filename extension to determine what the encoding was.
Fix #19
> Support markdown documents

- app/api/types.go
- app/api/types_test.go
- app/pkg/analyze/analyzer.go
- app/pkg/analyze/analyzer_test.go
* Prefactoring in preparation for #69
* We want our forth coming PWA to be able to depend on the types but we don't want to pull in other parts of the analyze package.
> Prefactor: move BlockLog and LogEntry into api package

- app/pkg/application/app.go
- app/pkg/eval/evaluator.go
- data/eval/gcp/gcb_hydros.foyle
- data/eval/gcp/gcb_hydros_by_image.foyle
- experiments/norag.yaml
* We were processing each file multiple times because we weren't properly populating a new array with the results
of FindYamlFiles
> Fix bug in Application.ApplyPaths

- frontend/vscode/web-assets/image.yaml
We need to include the vscode web assets image in each release. Otherwise foyle will be unable to download the assets because an image with the tag is missing.
Related to #99
> Include the vscode-web-assets image in each release

- app/pkg/config/config.go
* When a user runs assets download they may not have created a .foyle/config.yaml file yet
* As a result the ConfigDir will be the empty string and assets will be put into the local directory
* To solve this if the ConfigFile is empty we return the default config directory.
Fix #103
> Assets download shouldn't use CWD if there is no config file

- app/pkg/agent/agent.go
- app/pkg/oai/client_test.go
* Log Agent.Generate errors so we have clear error messages in the event the OpenAI request fails.
Fix #112
> Improve logging of OpenAI errors

- app/api/types.go
- app/pkg/docs/ids.go
- app/pkg/runme/converters/blocks_to_cells.go
- app/pkg/runme/converters/cells_to_blocks.go
- app/pkg/runme/converters/cells_to_blocks_test.go
- app/pkg/runme/converters/const.go
- app/pkg/runme/proxy.go
- developer_guides/runme.md
* RunMe uses ULIDs for cell ids. If we switch to using ULIDs we can be consistent with what RunMe does and avoid having two different types of ids for blocks. This will avoid a lot of headaches.
Related to #110
> Use ULIDs for block ids

- app/cmd/logs.go
- app/pkg/analyze/analyzer.go
- app/pkg/analyze/analyzer_test.go
- app/pkg/config/config.go
- app/pkg/learn/learner.go
- app/pkg/runme/proxy.go
- data/eval/runme/logs.md
- developer_guides/runme-01HYZVHZ41CAN75B22CRC9D9J6.md
- developer_guides/runme-01HZ0KBGBKTSRH95B2E3TWH16S.md
- developer_guides/runme.md
- docs/content/en/docs/learning/_index.md
* Fix training on RunMe logs #110 
* We need to allow Foyle to be configured with the directory of the RunMe logs
* Add LearnerConfig to Foyle config with the logs directory
* Fix a bug in analyze preventing BlockLogs from being updated with the executed block when using RunMe
* The bug was that when looking for the last execution trace; we weren't considering RunMe traces
* Update the RunMe developer guide
* Update the docs
> Fix retraining for RunMe

- app/go.mod
- app/go.sum
- app/pkg/config/config.go
- app/pkg/learn/in_memory.go
- app/pkg/learn/learner.go
- docs/content/en/docs/learning/_index.md
- tech_notes/tn007_shared_learning.md
Support loading training examples from GCS
* This makes it easy to create a shared AI among a team.
* Refer to tn007_shared_learning.md for the design
* A limitation of the current approach is that we only load examples from shared storage that weren't created by the user
at startup.
Fix #145
> Support loading training examples from GCS

- app/pkg/agent/agent.go
- app/pkg/agent/agent_test.go
- app/pkg/application/app.go
- app/pkg/eval/evaluator.go
- app/pkg/learn/in_memory.go
- app/pkg/learn/in_memory_test.go
- app/pkg/llms/completer.go
- app/pkg/llms/doc.go
- app/pkg/llms/errors.go
- app/pkg/llms/vectorizer.go
- app/pkg/oai/completer.go
- app/pkg/oai/embeddings.go
* Define two higher level interfaces Completer and Vectorizer to handle generating completions and computting embeddings.
* This will make it easier to support different LLM providers because we can just implement those interfaces for new providers.
Related to #158
> Prefactor to support different LLM providers

- app/api/config.go
- app/go.mod
- app/go.sum
- app/pkg/application/app.go
- app/pkg/config/config.go
- app/pkg/replicate/client.go
- app/pkg/replicate/completer.go
- app/pkg/replicate/completer_test.go
- app/pkg/replicate/vectorizer.go
- app/pkg/replicate/vectorizer_test.go
- docs/content/en/docs/replicate/_index.md
* Implement the completer and vectorizer interfaces for Replicate
* For the completer API we can use Replicate's OpenAI proxy to access LLAMA3 https://lifeboat.replicate.dev/
* There are embedding models on Replicate but they aren't kept warmed up so they are super slow
so we should probably use an embedding model from someplace else.
* Good example of why we don't want to source models from a single provider.
Anthropic recommends voyage AI
https://www.voyageai.com/?ref=anthropic
Related to #158
> Support using Replicate

- app/pkg/analyze/analyzer.go
- app/pkg/application/app.go
* App.shutdown should ensure Analyzer is non-nill before invoking it; otherwise we get a nill pointer dereference
* Analzyer should include a stack trace in its error message.
> Minor bugfixes

- app/pkg/agent/agent.go
- app/pkg/agent/tracer.go
- app/pkg/analyze/analyzer.go
- app/pkg/analyze/analyzer_test.go
First step of fixing tracing and learning to work with streaming.
We need to give each generate request within a streaming request a unique trace id.
Related to #180
Related to #167
> Give each streaming generate request a unique trace id

- app/pkg/analyze/reader.go
- app/pkg/analyze/reader_test.go
* In actual use we are starting to see bufio.Scanner errors from the analyzer
```
2024-08-06T12:50:15.653-0700    ERROR   analyze/analyzer.go:189 Error processing log file       {"path": "/Users/jlewi/.foyle/logs/raw/foyle.logs.2024-08-06T09:33:33.json", "error": "failed to scan file /Users/jlewi/.foyle/logs/raw/foyle.logs.2024-08-06T09:33:33.json: bufio.Scanner: token too long", "errorVerbose": "bufio.Scanner: token too long\nfailed to scan file /Users/jlewi/.foyle/logs/raw/foyle.logs.2024-08-06T09:33:33.json\ngithub.com/jlewi/foyle/app/pkg/analyze.readLinesFromOffset\n\t/Users/jlewi/git_foyle/app/pkg/analyze/reader.go:35\ngithub.com/jlewi/foyle/app/pkg/analyze.(*Analyzer).processLogFile\n\t/Users/jlewi/git_foyle/app/pkg/analyze/analyzer.go:203\ngithub.com/jlewi/foyle/app/pkg/analyze.(*An …
```
> Increase buffer size to fix bufio.Scanner: token too long

- app/pkg/learn/learner.go
We weren't adding the correct error to the list of errors that got reported. We ended up adding a nil error which caused panics down the line.
> Fix panic and error reporting in learner.Reconcile. 

- app/go.mod
- app/go.sum
- app/pkg/learn/learner.go
* Upgrade monogo to pull in a fix https://github.com/jlewi/monogo/commit/814ce2b6c0b971be0ae3ec29542e7ec14775ffd9
* This was causing the panics when trying to get the errors for the reconciler
* Related to #208;
> Don't hide the error when reconciling examples.

- app/go.mod
- app/go.sum
- app/pkg/learn/learner.go
* An example file can be overwritten.
* A block could be executed multiple times. Each time a block is executed it could trigger feedback and learning. In this case, the learner would be invoked and we'd want to use the latest value of the cell to learn from.
* Prior to https://github.com/jlewi/monogo/pull/22 FileHelper.NewWriter would throw an error if the file already exists. That PR changed the semantics to truncate the file if it already exists.
* So by upgrading monogo we should allow overwriting of examples if they already exist.
Fix #205
> Allow Example Files To Be Overwritten

- app/pkg/config/config.go
- docs/content/en/docs/getting-started/_index.md
We decided  to change the default because 8080 is over used and likely to conflict with other locally running services.
> Change default HTTP port to 8877. 

- app/pkg/analyze/analyzer.go
- app/pkg/analyze/analyzer_test.go
The problem is described in detail here
https://github.com/jlewi/foyle/issues/215#issuecomment-2356987795
In #241 I changed where the learner gets notified of a block to process. Rather notifiying it when updating a blockLog with the generated block, I moved the update to do it after an execution event was processed.
My assumption was that by the time the execution event gets processed the BlockLog has already been processed.
But that's not guaranteed because we read the log lines in chunks and only update the blocklog with the generated block after reading the entire chunk. However, the executed field of the blockLog is updated as soon as the line is processed. As a result, we were notifying the learner after the first execution event at which point the block log hasn't been updated with …
> Fix Race Condition In Learning

- app/pkg/analyze/session_builder_test.go
- app/pkg/application/app.go
- app/pkg/config/config.go
- app/pkg/config/config_test.go
- app/pkg/config/test_data/partial.yaml
- app/pkg/server/server.go
* Fix #249
* The bug was the function UseRAGEnabled was using a hard coded value for the default rather than the constant. As a result, when we recently changed the default to be true it wasn't actually enabled by default.
* Refactor viper processing so its easy to test configuration in a unittest
* We want to be able to create instances of viper using viper.New in the unittest so that we don't have to only use the global viper instance.
* To support that we refactor InitViper into a separate function which takes as an argument *viper.Viper
> Enable RAG by default

- app/pkg/learn/in_memory.go
- app/pkg/learn/in_memory_test.go
* Because we divide by 1.5; in the edge case were we have 1 example we'd end up rounding down to 0 which will cause problems when we try to initialize a matrix to that size. Fix #248
> Ensure embeddings matrix is never initialized with zero dimensions

- app/pkg/learn/in_memory.go
When learner is initialized at program startup we want to initialize an empty array because learned examples might arrive during program execution.
If we have a nil matrix to store them we will get a segfault.
Ensuring a matrix is always initialized at startup is one way to solve this.
Follow up to #252
> Fix segfault in learner.

- app/pkg/agent/agent.go
- app/pkg/agent/agent_test.go
- app/pkg/config/const.go
* Use gpt4-o-mini by default to lower costs.
* gpt4-o-mini is more than an order of magnitude cheaper than gpt4-o
* .15 / million input tokens vs $5 / million input tokens
* .6 / million output tokens vs $15 / million output tokens
* In the case where OAI can't determine an apporpriate command it often just outputs the output tag </output>. This is sometimes included in a code block so our postprocessing doesn't remove it and turn it into an empty response
* Fix the post-processing to remove this.
Fix #264
> Use gpt4-o-mini by default and filter out </output> tags

- app/pkg/agent/agent.go
- app/pkg/agent/agent_test.go
* I'm observing cases where we have a non empty suggested cell which ends up getting deleted.
* It looks like this happens for one of two reasons
* The model responses with an empty code block which doesn't get filtered out
* We return a response with no blocks in it
* We should filter these out.
* This means we bias towards generating irrelvant suggestions rather than no suggestions.
* Right now I think this is helpful because otherwise people might get confused and wonder whether Foyle is working.
Here's the supporting notebook
https://gist.github.com/jlewi/31857545ec62b36d2949ccd904918d53
> Filter out blank responses

- app/cmd/config.go
- app/pkg/config/config.go
- app/pkg/config/test_data/partial.yaml
- app/pkg/config/update.go
- app/pkg/config/update_test.go
* config set agent.model wasn't working when you use "--config" to specify a non default config file
* The break occured because of https://github.com/jlewi/foyle/blob/e03b8fe40b65f777de3b7c9ed02b612403c9c71f/app/pkg/config/config.go#L366
* That change meant InitViper was no longer operating on the global instance.
* However this line https://github.com/jlewi/foyle/blob/e03b8fe40b65f777de3b7c9ed02b612403c9c71f/app/cmd/config.go#L60 which was modifying the configuration was using the global instance
* This PR fixes this by being explicit about the instance of viper used.
* The unittest verifies we correctly modify the configuration
> Fix bug in config set when flag --config is provided

- app/pkg/agent/agent.go
- app/pkg/eval/evaluator.go
- app/pkg/eval/judge.go
* In #271 we added a SelectedIndex field to the GenerateCellsRequest to specify which cell in the notebook is active.
* If we don't set it then it ends up defaulting to 0. In which case we end up truncating the notebook to just the first cell and then the evaluation results end up being all wrong.
* Fix a bug in the evaluator runGenerate;  if Agent.GenerateCells returns an error we need to abort execution of runGenerate otherwise we get a panic later in runGenerate when we try to access the message in the response.
> Evaluation needs to include the SelectedIndex in the GenerateCellsRequest

- app/Makefile
- app/pkg/agent/agent.go
- app/pkg/docs/blocks.go
- app/pkg/docs/blocks_test.go
- app/pkg/eval/evaluator.go
- app/pkg/learn/in_memory.go
- app/pkg/learn/in_memory_test.go
- app/pkg/learn/learner.go
- app/pkg/learn/learner_test.go
- app/pkg/llms/query.go
- app/pkg/llms/vectorizer.go
- app/pkg/oai/embeddings.go
- app/pkg/oai/errors.go
- app/pkg/oai/errors_test.go
* Prior to this document we were computing the embeddings using the entire notebook.
This would lead to context exceeded errors on longer documents.
* This had two negative impacts
1. We stop learning from long documents because we no longer compute embeddings for the document
1. When making suggestions we don't embed up retrieving any documents from RAG because we can't compute the embeddings
for the current document
* In Example.Query we were including the full document which would then be injected into the context when generating new suggests
* This can end up using a lot of tokens and potentially confusing the agent when generating new suggestions
* Use a simple algorithm to shorten the example. The aglorithm is as follows
* Include the current selected cell
* Keep including previous …
>     Fix failures to compute embeddings too much context & Shorten RAG Results

- app/pkg/analyze/analyzer.go
- app/pkg/analyze/analyzer_test.go
- app/pkg/application/app.go
- app/pkg/config/config.go
- app/pkg/config/config_test.go
- app/pkg/config/update_test.go
- app/pkg/eval/evaluator.go
- app/pkg/eval/judge.go
- app/pkg/eval/tracer.go
Per #301, our experiments were really slow. We were observing times of approximately 30s to 60s to process individual examples. With the new dataset of 424 examples it would take ~7hours to run an experiment; significantly impeding iteration.
This PR instruments evaluation with OTEL so that we can see the bottlenecks in the code. Below are some graphs.
The graph below shows the P95 latency of processing evaluation examples. We can see its about 30s.
Below is a heatmap showing the duration of waitForBlockLog
We can see that its about 20s-30s so it accounts for a large portion of the duration.
A big source of the latency is the Analyzer uses a rate limiting queue for reprocessing the logs. The max delay is 30s so we are probably reprocessing the logs and 30s intervals. So to speed it up we …
> Speedup Eval - Instrument With Otel

- app/pkg/eval/evaluator.go
- app/pkg/eval/results_manager.go
CellsMatchResult can be nil. I think this is the result of default values not being serialized in the protojson.
Update the results manager to include default values when serializing to JSON. This should make SQL queries easier.
> Fix bug in evaluation report

- app/pkg/agent/agent.go
- app/pkg/agent/client.go
- app/pkg/agent/client_test.go
- app/pkg/eval/evaluator.go
* During evaluation we are seeing ocassional timeouts on the server due to the HTTP read/write timeout occuring. It looks like this might happen because ChatGPT takes a really long time to respond occassionally.
* Update StreamGenerate and GenerateCells to return DeadlineExceeded to indicate a server timeout
* Implement a unaryinterceptor to automatically retry requests based on the status code.
* The retry is pretty simplistic; its a fixed backoff.
* Fix a bug in Agent.go where we aren't correctly logging one of the level1 assertions.
> Add retries to evaluator client

- cicd/README.md
- cicd/releaser/config.yaml
- cicd/releaser/cronjob.yaml
- cicd/releaser/kustomization.yaml
- cicd/releaser/namespace.yaml
- cicd/releaser/serviceaccount.yaml
* Use a cronjob to perioidically run hydros to release Foyle.
> Create a cronjob to autorelease Foyle.

- app/pkg/agent/prompt.tmpl
- app/pkg/agent/test_data/examples.txt
- app/pkg/agent/test_data/no_examples.txt
- app/pkg/docs/const.go
- app/pkg/docs/converters.go
- app/pkg/docs/converters_test.go
- app/pkg/docs/tailer.go
- app/pkg/docs/tailer_test.go
Cell outputs can be very long. For example, if we run a query (gcloud, SQL, etc...) the output could be very verbose. This output could eat up the entire context allocated for the input document. As a result, we might not have sufficiently meaningful context to prompt the model.
There was another bug in our doc tailer. We were applying character limits to the rendered markdown. We were imposing this by tailing the lines. This could produce invalid markdown. For example, we might end up truncating the document in the middle of a code block so we wouldn't have the opening triple quotes for the code block. We might also include the output of the code block without including the code that it is output for.
First, we impose character limits in a way that is aware of cell boundaries. We move …
> Improve Handling Of Long Outputs

- app/pkg/runme/converters/blocks_to_cells.go
- app/pkg/runme/converters/cells_to_blocks_test.go
* Forcing cells to be non-interactive was a temporary fix for the fact that the output wasn't included in Foyle completion requests (#286)
* This is now fixed in the frontend so that the output of interactive cells is included in the requests to Foyle
* We don't want to default to non-interactive cells because non-interactive cells don't show stderr
Related to jlewi/foyle/issues/286
> Stop forcing cells to be non-interactive

- app/pkg/agent/agent.go
I think we get this issue (#319) because we check whether the context is cancelled before generating an AI response and then try to return the response. However, in between the initial check and actually having the response to send the context could have been cancelled.
So check if the context is done. before sending the response.
Fix #319
> Fix Panic: Write After Handler Closed

- app/pkg/agent/agent.go
- app/pkg/docs/const.go
- developer_guides/runme.md
* The purpose of this PR is to add logging to confirm that #309 is fixed; i.e. that when triggering on cell execution for interactive (and non interactive cells) the output is included in the request
* This PR adds logging that checks if the selected cell has non-empty stdout if its empty we log a message. The presence of these log messages thus indicates cell execution triggered completion that included no stdout.
* This will include false positives because in certain cases the command may not produce any output.
* With this logging I was unable to reproduce any instances where completion was triggered by cell execution but stdout wasn't included.
* This PR fixes a bug in the mimetype for stdout; there was an extra space. I don't think that actually impacted processing because that …
> Add logging to confirm that stdout isn't empty when triggering on cell execution

- docs/content/en/docs/operator-manual/troubleshoot_learning.md
fix: Correct API endpoint and adjust localhost configuration (Resolves #346)
This pull request addresses the following issues related to the API call and local development setup:
•	API Endpoint Fix: Updated the endpoint path from foyle.logs.SessionsService/GetSession to api/GetSession for proper routing.
•	jq Syntax Correction: Added a period (.) after jq to ensure JSON output is parsed and displayed correctly.
•	Protocol Adjustment: Replaced https:// with http:// for localhost to avoid unnecessary SSL complications during local testing.
```
CONTEXTID=01J7S3QZMS5F742JFPWZDCTVRG
curl -s -X POST https://localhost:8877/foyle.logs.SessionsService/GetSession -H "Content-Type: application/json" -d "{\"contextId\": \"${CONTEXTID}\"}" | jq.
```
```
CONTEXTID=01J7S3QZMS5F742JFPWZDCTVRG
curl -s -X …
```
> fix: Correct API endpoint and adjust localhost configuration (Resolves #346)

- docs/README.md
- docs/content/en/settings/_index.md
- docs/layouts/partials/page-meta-links.html
Create a link in the right hand side bar to open up the current page in VSCode. If Runme is installed this will open it up as a notebook.
Here's how this work
* VSCode registers to handle URI "vscode://" so you can use a URI like "vscode://file/some/file.md" to open that file in VScode.
So we customize the partial [page-meta-links.html](https://github.com/google/docsy/blob/main/layouts/partials/page-meta-links.html). This shows up in the right hand navigation bar and shows links to "edit the page". We add a link to this to open in VSCode using a vscode URI.
A limitation of "vscode://file" URIs is that they only work with absolute paths. So we need to know the BasePath where the repo is cloned in order to have the correct path. This will be different for every user. We can store this in …
> Create a link to open up the pages in vscode
